version: 0.2
phases:
  install:
    commands:
      # Update libs
  pre_build:
    commands:
      # # Install dependencies
  build:
    commands:
      # login to prevent docker rate limit. Credentials passed in as env var from AWS secret manager
      - docker login --username $DOCKER_USER -p $DOCKER_PASSWORD
      - docker build .
      - export VPP_VERSION=$(docker run $(docker build -q . --target version))
      - export TAG=v$(echo $VPP_VERSION | sed 's/~/-/g')
      - docker build -t ghcr.io/${{github.repository}}/vpp:${TAG} . --target vpp
      - docker build -t ghcr.io/${{github.repository}}/vpp-dbg:${TAG} . --target vpp-dbg
