---
name: ci
on:
  push:
    branches:
      - main
    tags:
      - v*
    paths-ignore:
      - '**.md'
  pull_request:
    paths-ignore:
      - '**.md'
jobs:
  generate:
    name: generate
    runs-on: ubuntu-latest
    # These permissions are needed to interact with GitHub's OIDC Token endpoint.
    permissions:
      id-token: write
      contents: read
    steps:
      - name: Check out code
        uses: actions/checkout@v2
      - name: Configure AWS credentials from Test account
        uses: aws-actions/configure-aws-credentials@v1
        with:
          role-to-assume: ${{ secrets.OIDC_ROLE_TO_ASSUME }}
          aws-region: ${{ secrets.AWS_REGION }}
      - name: Run CodeBuild
        uses: aws-actions/aws-codebuild-run-build@v1
        with:
          project-name: github-actions-example
          buildspec-override: buildspec.yaml
          env-vars-for-codebuild: |
            custom,
            requester,
            event-name
        env:
          custom: my environment variable
          requester: ${{ github.actor }}
          event-name: ${{ github.event_name }}
      - uses: actions/setup-go@v1
        with:
          go-version: 1.15.3
      - name: Generate files
        run: go generate ./...
      - name: Check for changes in generated code
        run: |
          git diff -- binapi || (echo "Rerun go generate ./... locally and resubmit" && exit -1)
      - name: Go Build
        run: go build ./...
